#-----------------SETUP FOLDER STRUCTURE-----------------

# Instead of using "all" you should/could specify server names.
# it's a little bit more safe.

- hosts: all
  user: serveradmin
  become: true

  vars:
    docker_compose_version: "1.28.5"
    serveradmin_path: /home/serveradmin/docker
    server_owner: serveradmin
    server_group: 1000
    serveradmin_dirs:
      - /sabnzbd
      - /shared/DockerCompletedMovies"
      - /shared/DockerCompletedTVshows
      - /shared/remotemovies
      - /shared/remotekidsmovies
      - /shared/remotetvshows
      - /shared/remoteESXi
      - /plex
      - /sonarr
      - /radarr

  tasks:
    - name: create directories owned by serveradmin, group serveradmin
      file:
        path: "{{ serveradmin_path }}/{{ item }}"
        state: directory
        owner: "{{ server_owner }}"
        group: "{{ server_group }}"
        mode: "u=rwx,g=rwx,o=rx,g+s"
      loop:
        - "{{ serveradmin_dirs }}"

    - name: Fix folder permissions for SABnzbd. sgid bit mode.
      file:
        path: "{{ serveradmin_path }}/sabnzbd"
        state: directory
        owner: "{{ server_owner }}"
        group: "{{ server_group }}"
        mode: 2775
      loop:
        - sabnzbd
        - sonarr
        - radarr
        - plex
